export { default as Card } from './Card'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Home } from './Home'
export { default as About } from './About' 
export { default as Menu } from './Menu'
export { default as Projects } from './Projects'
export { default as Pill } from './Pill'
export { default as Skills } from './Skills'
export { default as Contact } from './Contact'
export { default as SocialLinks} from './SocialLinks'
export { default as Technologies} from './Technologies'